[build]
  command = "python build.py"
  publish = "output"
  
[build.environment]
  PYTHON_VERSION = "3.8"
  NETLIFY = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python build.py && python -m http.server -d output"
  targetPort = 8000
  port = 8000
  publish = "output"
  autoLaunch = true